### ISSUE TITLE
Installation "Failed to Download Rustls v0.20.6"

### ISSUE THREAD

**Issue by stevesec** [OPENCYBER-FR/RustHound#1]
In attempting to install RustHound, hit an error and stated that it "failed to download rustls v0.20.6"

```
error: failed to download `rustls v0.20.6`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `**/registry/src/github.com-1ecc6299db9ec823/rustls-0.20.6/Cargo.toml`

Caused by:
  feature `resolver` is required

  consider adding `cargo-features = ["resolver"]` to the manifest
```
### Steps to reproduce

1. Grab the latest from GitHub via git clone <>
2. cd <>
3. cargo build --release as discussed in [URL](https://www.opencyber.com/rusthound-data-collector-for-bloodhound-written-in-rust/)

Current version(s): 
- Cargo 1.46.0

Please let me know if there is anything I can do to help with this error or if you need more information. Thank you!

**Comment by sebrink** [comment]
@stevesec for what it's worth, this worked for me with Cargo 1.64.0

**Comment by g0h4n** [comment]
@stevesec please use the last version of Cargo.
Indeed some features works only with the last version.
I mark the issue as closed.

**Comment by stevesec** [comment]
Agreed, closed, works on the latest version of Cargo.
