### ISSUE TITLE
Unique issue with too many LDAP objects - [BUG]

### ISSUE THREAD

**Issue by AnubisSec** [OPENCYBER-FR/RustHound#10]
Hey there, love the idea of this tool!

I've run into an issue, which might not be as common enough to warrant a true fix, but when running in a domain with 100's of thousands of LDAP objects, the process ends up dying around averagely around 410k objects retrieved

```
[2022-12-29T16:21:17Z INFO  rusthound::ldap] Starting data collection...
LDAP objects retreived: 405944#                                                                                                                                           
56821 killed     target/release/rusthound -d xxx.com -u 'xxxxx' -p  --adcs -```

```
```
[2022-12-29T18:24:42Z INFO  rusthound::ldap] Starting data collection...
⢀ LDAP objects retreived: 56783#                                                                                                               
.  LDAP objects retreived: 57480#                                                                                                               
⠐ LDAP objects retreived: 429216#                                                                                                              
Killed
$ 
```

Let me know if you'd like any other data points!

**Comment by AnubisSec** [comment]
oh apologies, i see this is referenced in #7 , feel free to close if already working on it

**Comment by g0h4n** [comment]
Hello @AnubisSec,

Thanks for your message.
Yes, indeed this issue is the same as #7
I'm currently working on it :)

I'm going to close this one but for my information and to help me in fixing this one could you please tell me how much RAM you have on your computer that ran the data collection with RustHound?

Thanks!

**Comment by AnubisSec** [comment]
Thans @g0h4n!

And sure, i tried on my Mac with 32GB of RAM, and a VM with 8GB or RAM

**Comment by g0h4n** [comment]
@AnubisSec thanks for your feedback,
I note as duplicated with issue #7
I am working on it to use a serialized swap file instead of RAM
