### ISSUE TITLE
No "Blazing fast" in readme

### ISSUE THREAD

**Issue by gomep342** [OPENCYBER-FR/RustHound#2]
I was very disappointed when I opened the collector for bloodhound on rust, went to the page, did ctrl f and did not find "blazing fast" on it
Now I'm not sure if I'm written in rust at all
Fix it ASAP

**Comment by g0h4n** [comment]
Hello @gomep342,
The readme has been updated with new statistics. Is that what you were expecting to see?
[https://github.com/OPENCYBER-FR/RustHound#rocket-statistics](https://github.com/OPENCYBER-FR/RustHound#rocket-statistics)

**Comment by gomep342** [comment]
nice
thx
