### ISSUE TITLE
thread 'main' panicked at src/objects/user.rs:341:36:

### ISSUE THREAD

**Issue by Acebond** [OPENCYBER-FR/RustHound#35]
![image](https://github.com/user-attachments/assets/0384f2d2-da30-499f-a832-ce41794f71f1)

I was trying RustHound and it crashed and with the error below:

 Parsing LDAP objects: 0%
thread 'main' panicked at src/objects/user.rs:341:36:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)

**Comment by g0h4n** [comment]
Hello @Acebond,
Thank you for your message.

Could you please open this issue in the [RustHound-CE](https://github.com/g0h4n/RustHound-CE) repository?
This issue affects only the CE version, not the Legacy version.

**Comment by Acebond** [comment]
Done.
