### ISSUE TITLE
Json Files Incomplete or Unreadable by Bloodhound

### ISSUE THREAD

**Issue by 416e6f6e5368656c6c** [OPENCYBER-FR/RustHound#5]
Json files processed post-collection appear to be incompatible with bloodhound and also unprocessable by JQ utility.

**Comment by 416e6f6e5368656c6c** [comment]
Looking back at the files it actually appears the making of the file was not complete the file cuts out in the middle of an AD object. Maybe too large of a domain?

**Comment by barney0** [comment]
Hi, could you please describe what you have done please? I tried to reproduce what you seem to have done and it seems that you are trying the "Import Graph" feature instead of the "Upload Data". If it is not the case, just give us some more information.

What version of bloodhound are you using?

On our side it works well!

**Comment by g0h4n** [comment]
Hi @416e6f6e5368656c6c and thanks for your report.

I think I have an idea where is the problem.
Could you please test to collect datas again but without the zip argument? 

And if possible, could you please send me the number of objets in your LDAP ?

**Comment by 416e6f6e5368656c6c** [comment]
Hello, i am using bloodhound version 4.1.0, similar to sharphound collectors I was trying to drag and drop the ZIP into bloodhound. some files work and some say that they are incompatible and after looking at the file its because they are incomplete. The file cuts out in the middle of parsing and object. 

BUT took off the zip argument and uploaded the raw json files and it worked ! thank you, awesome tool!

**Comment by g0h4n** [comment]
Hello @416e6f6e5368656c6c,

I think I've fixed that with this commit: [https://github.com/OPENCYBER-FR/RustHound/commit/3b3225d5a3112f0d47153db43c3182a174ae2303](https://github.com/OPENCYBER-FR/RustHound/commit/3b3225d5a3112f0d47153db43c3182a174ae2303).

More information about write_all() function here: [https://doc.rust-lang.org/nightly/std/io/trait.Write.html#method.write_all](https://doc.rust-lang.org/nightly/std/io/trait.Write.html#method.write_all)
