### ISSUE TITLE
LDAP ConnectionRefused

### ISSUE THREAD

**Issue by PairyLyn** [OPENCYBER-FR/RustHound#6]
Sorry, I got a problem: "LDAP ConnectionRefused", How can I solve it

![U1_`BF0(SU $ V37YPG0(YS](https://user-images.githubusercontent.com/69453614/199385731-119755aa-3ee0-46d0-906b-4a4d50019d6c.png)

**Comment by g0h4n** [comment]
Hello,

The current code "10061" means that the Active Directory is rejecting your connection.
Could you please send me more information about the Active Directory environement?

If your AD allows LDAPS connections try: 
`
rusthound.exe --domain WSX.COM -u 'user@wsx.com' -p 'password' -o output --ldaps
`

If you don't have DNS for WSX.COM, then add the ip address:
`
rusthound.exe --domain WSX.COM -i  102.168.111.200 -u 'user@wsx.com' -p 'password' -o output
`

If your Windows computer is already in the domain WSX.COM, thentry to use GSSAPI connection with the following command:
(Where "AD1" is the hostname of your AD.)
`
rusthound.exe --domain WSX.COM --fqdn-resolver AD1.WSX.COM -o output 
`

**Comment by PairyLyn** [comment]
like this:
![image](https://user-images.githubusercontent.com/69453614/199439173-e113db4c-d25a-4b8d-95bf-ac62b9f31bfd.png)
![image](https://user-images.githubusercontent.com/69453614/199439321-c5baf353-ac4c-4185-acc0-ecb2edf36ff4.png)

**Comment by g0h4n** [comment]
@PairyLyn thanks for your feedback.

Ok so the last command works well with GSSAPI.
For the bind connection please try the following command :

`
rusthound.exe --domain WSX.COM -u 'test1@wsx.com' -p '@Password' -i 192.168.111.200 --ldaps -o wsx_output -z -v
`

That will try with the LDAPS connection and IP address as well.

**Comment by PairyLyn** [comment]
@g0h4n thanks , but it is still "10054". 😢
![image](https://user-images.githubusercontent.com/69453614/199448139-36b1b890-aab3-487f-9c90-10183c7b64c4.png)

**Comment by g0h4n** [comment]
**10054** _means: An existing connection was forcibly closed by the remote server or application._ 

Maybe your Active Directory doesn't allow bind connections.
Do you know if your AD allows ldap (389 port) connections ?

If yes only the following command will works:
`
rusthound.exe --domain WSX.COM -u 'test1@wsx.com' -p '@Password -o wsx_output -z -v
`

**Comment by PairyLyn** [comment]
Maybe it has something to do with "PRINCIPAL"?

![image](https://user-images.githubusercontent.com/69453614/199464195-b86a4c4b-1ead-4082-b2cf-fa78d9c624cc.png)

389 can be connected:
![image](https://user-images.githubusercontent.com/69453614/199463768-774dc2fc-3c15-4eb4-a333-291b1b273c7e.png)

A solution?
![image](https://user-images.githubusercontent.com/69453614/199462846-b952fd73-961d-403e-b19d-ff2c5c9aebe0.png)

**Comment by g0h4n** [comment]
Ok I see, thanks for all informations.

Could you please try:

`
rusthound.exe --domain WSX.COM -u 'CN=test1,CN=Users,DC=WSX,DC=COM' -p '@Password' -o wsx_output -z -v
`

**Comment by PairyLyn** [comment]
Thanks for your suggestion, but it hasn't been resolved.😂😂

**Comment by g0h4n** [comment]
Haha, I will check to reproduct it on my lab.
And I will look at the "PRINCIPAL". Thanks ! :)

**Comment by g0h4n** [comment]
Hello @PairyLyn,

I reproduced the issue on my lab.
And it seems that it only comes from **simple quote '** or **double quote "** for RustHound (Windows) arguments from **cmd.exe**.

### First example with simple quote on **cmd.exe**:
`rusthound.exe -d essos.local -u 'daenerys.targaryen@essos.local' -p 'BurnThemAll!' -o output2 -zv`
![nok_cmd_simple_quote](https://user-images.githubusercontent.com/18140652/204773011-8a546662-8dd5-499e-87a3-df52c87a2f4c.jpg)

### Second example without simple quote on **cmd.exe**:
`rusthound.exe -d essos.local -u daenerys.targaryen@essos.local -p BurnThemAll! -o output2 -zv`
![ok_cmd_no_simple_qote](https://user-images.githubusercontent.com/18140652/204773186-31994890-1992-40e8-8532-3a3e5c3e5905.jpg)

### Last example with simple quote on **powershell.exe**:
`.\rusthound.exe -d essos.local -u 'daenerys.targaryen@essos.local' -p 'BurnThemAll!' -o output2 -zv`
![ok_powershell_simple_qote](https://user-images.githubusercontent.com/18140652/204773294-00facffa-8f03-4e43-87b2-b619831d1fc9.jpg)

### Solution:
Please don't use simple quote or double quote from **cmd.exe** for arguments content.

If is ok for you I will close this issue. :smile:

**Comment by PairyLyn** [comment]
Sorry, I noticed it a little late, but thanks for your answer, it can run successfully with powershell. 😄😄😄
