### ISSUE TITLE
Crashing when parsing group

### ISSUE THREAD

**Issue by moscowchill** [OPENCYBER-FR/RustHound#8]
Love this tool
Any idea why it would crash multiple times when parsing groups?
![image](https://user-images.githubusercontent.com/72578879/207027052-18e549ca-5f4a-47e0-94a1-36dc9995ecdb.png)

**Comment by g0h4n** [comment]
Could you please run RustHound again with -vv for **Trace** output and with **RUST_BACKTRACE** set to 1.

`export RUST_BACKTRACE=1 ; rusthound -d x.x (....) -vv`

And could you please send me the 5 lines before the crash?

I would like to know if it crashes all the time on the same group? 

Thanks!

**Comment by g0h4n** [comment]
Thanks for informations.

I don't understand why the security descriptor doesn't want to be parsed for your GUESTS group.
I take note, I removed the unwrap() to replace it with errors.

These will surely be more verbose.
The execution should not crash anymore but the objects that will have the error will not have their ACL.

Could you please do a test again?

`
cd RustHound
git pull
cargo b
target/debug/rusthound -d x.x -u username -p password -v -o /tmp/output
`

And if is possible could you please check the "**Aces**" value for "**GUESTS**" group in "**/tmp/output/x-x_groups.json**"?

Thanks.
